groups:
  - name: volume-node
    rules:
      # Alert for pv's fileystem getiing into read-only state while remounting on a particular node.
      - alert: VolumeNodeFileSystemIsReadOnly
        annotations:
          summary: 'Persistent Volume on node ''{{ $labels.node }}'' for persistent volume claim ''{{ $labels.persistentvolumeclaim }}'' is having read-only fielsystem while remounting'
          description: |-
            Persistent Volume's filesystem on node '{{ $labels.node }}' for persistent volume claim '{{ $labels.persistentvolumeclaim }}' has become read-only
        expr: |-
          kubelet_volume_stats_inodes * on(node) group_left(reason) problem_counter{reason="FilesystemIsReadOnly"} > 0
        for: 5m
        labels:
          severity: "critical"
      # Alert for pv's facing issues with ext4 filesystem on a particular nodes.
      - alert: VolumeNodeExt4Error
        annotations:
          summary: 'Persistent Volume on node ''{{ $labels.node }}'' for persistent volume claim ''{{ $labels.persistentvolumeclaim }}'' is having issues with ext4 fielsystem'
          description: |-
            Persistent Volume's on node '{{ $labels.node }}' persistent volume claim '{{ $labels.persistentvolumeclaim }}' encountering ext4 filesystem error
        expr: |-
          kubelet_volume_stats_inodes * on(node) group_left(reason) problem_counter{reason="Ext4Error"} > 0
        for: 5m
        labels:
          severity: "critical"
      # Alert for pv's facing issues with I/O on a particular node.
      - alert: VolumeNodeIOError
        annotations:
          summary: 'Persistent Volume on node ''{{ $labels.node }}'' for persistent volume claim ''{{ $labels.persistentvolumeclaim }}'' is having trouble with I/O'
          description: |-
            Persistent Volume on node '{{ $labels.node }}' for persistent volume claim '{{ $labels.persistentvolumeclaim }}' encountering errors w.r.t buffer I/O 
        expr: |-
          kubelet_volume_stats_inodes * on(node) group_left(reason) problem_counter{reason="IOError"} > 0
        for: 5m
        labels:
          severity: "critical"
      # Alert for pv's having some warning issued w.r.t ext4 filesystem.
      - alert: VolumeNodeExt4Warning
        annotations:
          summary: 'Persistent Volume on node ''{{ $labels.node }}'' for persistent volume claim ''{{ $labels.persistentvolumeclaim }}'' receiving ext4 filesystem warning'
          description: |-
            Persistent Volume on node '{{ $labels.node }}' receiving ext4 filesystem warning for persistent volume claim '{{ $labels.persistentvolumeclaim }}'
        expr: |-
          kubelet_volume_stats_inodes * on(node) group_left(reason) problem_counter{reason="Ext4Warning"} > 0
        for: 5m
        labels:
          severity: "critical"
